// Code generated by hero.
// source: /Users/jinmatt/go/src/github.com/jinmatt/twtrgo/http/template/src/body.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/jinmatt/twtrgo"
	"github.com/shiyanhui/hero"
)

func Render(tweets []*twtrgo.Tweet, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>TwtrGo! - A badly named twitter app!</title>
  </head>
  <body>
    `)
	_buffer.WriteString(`
  <nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">TwtrGo</a>
  </nav>

  <div class="container-fluid">
    `)
	for _, tweet := range tweets {
		_buffer.WriteString(`
        <ul class="list-group">
            `)
		_buffer.WriteString(`<li class="list-group-item">
    `)
		hero.EscapeHTML(tweet.Status, _buffer)
		_buffer.WriteString(`
    <span class="badge badge-primary badge-pill">`)
		hero.EscapeHTML(tweet.User.ScreenName, _buffer)
		_buffer.WriteString(`</span>
</li>
`)
		_buffer.WriteString(`
        </ul>
    `)
	}
	_buffer.WriteString(`
  </div>
`)

	_buffer.WriteString(`
  </body>
</html>
`)
	w.Write(_buffer.Bytes())

}
